const Categories = [
    'General Practitioner (GP)',
    'Internal Medicine Physician',
    'Pediatrician',
    'Cardiologist',
    'Dermatologist',
    'Orthopedic Surgeon',
    'Ophthalmologist',
    'ENT (Ear, Nose, and Throat) Specialist',
    'Gastroenterologist',
    'Obstetrician/Gynecologist (OB/GYN)',
    'Neurologist',
    'Psychiatrist',
    'Endocrinologist',
    'Rheumatologist',
    'Urologist',
    'Pulmonologist',
    'Nephrologist',
    'Oncologist',
    'Allergist/Immunologist',
    'Emergency Medicine Physician',
    'Anesthesiologist',
    'Radiologist',
    'Pathologist',
    'Infectious Disease Specialist',
    'Sports Medicine Physician',
  ];
  
  export default Categories;