const DoctorsData = {
    'General Practitioner (GP)': ['Dr. Smith', 'Dr. Johnson', 'Dr. Miller'],
    'Internal Medicine Physician': ['Dr. Davis', 'Dr. Wilson', 'Dr. Anderson'],
    'Pediatrician': ['Dr. Brown', 'Dr. Taylor', 'Dr. Evans'],
    'Cardiologist': ['Dr. Garcia', 'Dr. Martinez', 'Dr. Robinson'],
    'Dermatologist': ['Dr. Thomas', 'Dr. Hall', 'Dr. Perez'],
    'Orthopedic Surgeon': ['Dr. Lewis', 'Dr. Hill', 'Dr. Scott'],
    'Ophthalmologist': ['Dr. Green', 'Dr. Adams', 'Dr. Baker'],
    'ENT (Ear, Nose, and Throat) Specialist': ['Dr. White', 'Dr. Harris', 'Dr. Clark'],
    'Gastroenterologist': ['Dr. Young', 'Dr. Allen', 'Dr. Wright'],
    'Obstetrician/Gynecologist (OB/GYN)': ['Dr. King', 'Dr. Turner', 'Dr. Cooper'],
    'Neurologist': ['Dr. Ward', 'Dr. Morris', 'Dr. Watson'],
    'Psychiatrist': ['Dr. Murphy', 'Dr. Reed', 'Dr. Bailey'],
    'Endocrinologist': ['Dr. Long', 'Dr. Butler', 'Dr. Foster'],
    'Rheumatologist': ['Dr. Russell', 'Dr. Price', 'Dr. Bennett'],
    'Urologist': ['Dr. Simmons', 'Dr. Gray', 'Dr. James'],
    'Pulmonologist': ['Dr. Jenkins', 'Dr. Perry', 'Dr. Powell'],
    'Nephrologist': ['Dr. Coleman', 'Dr. Ford', 'Dr. Hamilton'],
    'Oncologist': ['Dr. Brooks', 'Dr. Hayes', 'Dr. Howard'],
    'Allergist/Immunologist': ['Dr. Diaz', 'Dr. Hayes', 'Dr. Murray'],
    'Emergency Medicine Physician': ['Dr. Alvarez', 'Dr. Bryant', 'Dr. Fox'],
    'Anesthesiologist': ['Dr. Kim', 'Dr. Nguyen', 'Dr. Patel'],
    'Radiologist': ['Dr. Griffin', 'Dr. Reynolds', 'Dr. Stone'],
    'Pathologist': ['Dr. Diaz', 'Dr. Hayes', 'Dr. Murray'],
    'Infectious Disease Specialist': ['Dr. Alvarez', 'Dr. Bryant', 'Dr. Fox'],
    'Sports Medicine Physician': ['Dr. Kim', 'Dr. Nguyen', 'Dr. Patel'],
  };
  
  module.exports = DoctorsData;